fixes #181: Giving exception if Labels contains space
neo4j/neo4j-jdbc pull request #182
Opened 2019-01-23 19:42 UTC by conker84

Changes:
- Fixed metadata resolution in case of backtick
- Fixed node property resolution in case of a property contains a backtick
- Fixed relationship property resolution in case of a property contains a backtick

2019-02-01 08:40 UTC, conker84 commented
@jexp updated!

2019-02-01 14:24 UTC, jexp requested changes

2019-02-01 14:24 UTC, jexp commented on neo4j-jdbc-bolt/src/main/java/org/neo4j/jdbc/bolt/BoltNeo4jResultSet.java
> +				value = this.current.get(key).get(property.replaceAll("`", ""));
move into a santiize function and use across labels, rel-types and property-keys

2019-02-01 14:24 UTC, jexp commented on neo4j-jdbc-bolt/src/main/java/org/neo4j/jdbc/bolt/BoltNeo4jResultSet.java
> +	private static final Pattern SPECIAL_CHARS = Pattern.compile("[^a-z0-9]", Pattern.CASE_INSENSITIVE);
misses underscore

also perhaps a positive pattern would be better? i.e. `^[a-z_][a-z0-9_]+$` + case insentistive ?

2019-02-01 14:24 UTC, jexp commented on neo4j-jdbc-bolt/src/main/java/org/neo4j/jdbc/bolt/BoltNeo4jResultSet.java
> +		String keyTemplate = SPECIAL_CHARS.matcher(key).find() ? FLATTEN_KEY_TEMPLATE_BACKTICK : FLATTEN_KEY_TEMPLATE;
shouldn't this be part of a `quote` method?

I think that would make it easier, like I do it in other places:

```
def quote (name:String) = if (name.isSpecial()) '`'+sanitize(name)+'`' else name
```

and use that in all places instead all the string formats?

2019-02-01 14:24 UTC, jexp commented on neo4j-jdbc-bolt/src/main/java/org/neo4j/jdbc/bolt/BoltNeo4jResultSet.java
> +		String keyTemplate = SPECIAL_CHARS.matcher(key).find() ? FLATTEN_KEY_TEMPLATE_BACKTICK : FLATTEN_KEY_TEMPLATE;
same for labels and rel-types

2019-02-01 14:24 UTC, jexp commented on neo4j-jdbc-bolt/src/main/java/org/neo4j/jdbc/bolt/BoltNeo4jResultSet.java
> +		String keyTemplate = SPECIAL_CHARS.matcher(key).find() ? FLATTEN_KEY_TEMPLATE_BACKTICK : FLATTEN_KEY_TEMPLATE;
isSpecial could also use the 

Character.isJavaIdentifierStart(c) 
Character.isJavaIdentifier(c)

instaed of regexp

2019-02-06 16:34 UTC, conker84 commented
@jexp updated!

2019-02-06 17:25 UTC, jexp approved these changes

2019-02-06 17:26 UTC, merged

2019-02-12 00:22 UTC, jexp commented on neo4j-jdbc/src/main/java/org/neo4j/jdbc/utils/SanitizeUtils.java
> +    public static String quote(String value) {
shouldn't we use this in more places?

2019-02-12 00:24 UTC, jexp commented on neo4j-jdbc/src/main/java/org/neo4j/jdbc/utils/SanitizeUtils.java
> +    public static String quote(String value) {
I.e. whenever we get a property key / label / rel-type that we add to a cypher statement?
 Also it should use `sanitize()` for the value before wrapping it in backticks.