feat: add more authentication schemes
neo4j/neo4j-jdbc pull request #596
Opened 2024-04-08 09:14 UTC by robsdedude

Add support for more auth schemes
 * `none` existed before, but was inferred from lacking user and password. Now needs to be configure explicitly.
 * `basic` as before
 * `bearer` for SSO tokens
 * `kerberos` for Kerberos tickets.

Fully custom auth schemes are currently not supported.

Closes: #579

2024-04-08 11:51 UTC, michael-simons requested changes
See inline comments.

Tests are great.

Thank you,

2024-04-08 11:51 UTC, michael-simons commented on docs/src/main/asciidoc/modules/ROOT/pages/configuration.adoc
> +|The realm to use for authentication. *NOT RECOMMENDED* for security reasons.
```suggestion
|The realm to use for authentication. *NOT RECOMMENDED* as URL query parameter for security reasons.
```

2024-04-08 11:51 UTC, michael-simons commented on docs/src/main/asciidoc/modules/ROOT/pages/configuration.adoc
> +a|The authentication scheme to use. *NOT RECOMMENDED* for security reasons. Currently supported values are:
```suggestion
a|The authentication scheme to use. *NOT RECOMMENDED* as URL query parameter for security reasons. Currently supported values are:
```

Same for the existing ones (Username and password). My bad oversight previously. Writing it that way makes it sound like it's not recommended at all.

2024-04-08 11:51 UTC, michael-simons commented on docs/src/main/asciidoc/modules/ROOT/pages/configuration.adoc
> +* `basic` for basic authentication.
Add a note that this is the default and implied if no other scheme is configured.

2024-04-08 11:51 UTC, michael-simons commented on neo4j-jdbc/src/main/java/org/neo4j/jdbc/Neo4jDriver.java
> +		static AuthScheme parse(String scheme) throws SQLException {
I prefer not have these additional parse methods on enums, as they put additional cognitive load on the casual reader, at least I always forget is the built in `valueOf` or something added.
I'd rather see this in a utility class as a static factory method.

See https://github.com/neo4j/neo4j-jdbc/blob/809083ee5c35ba001ab05e4b5c2cd1ab1e0a1b34/neo4j-jdbc/src/main/java/org/neo4j/jdbc/Neo4jDriver.java#L559 for example. 

would be nice to move this there.

2024-04-08 11:51 UTC, michael-simons commented on neo4j-jdbc/src/main/java/org/neo4j/jdbc/Neo4jDriver.java
> +		public String toString() {
I'd rather not have a custom to toString here at all, same reasons as above.
Rather improve the names.

You have `AuthScheme` already in the type name.
So no need to repeat it in the values, leaving `NONE`, `BASIC`,  `BEARER` and `KERBEROS`

They are totally fine as string representation.

Now, if you do the parsing case-insensitive as well, it all works.

2024-04-09 07:45 UTC, robsdedude commented on docs/src/main/asciidoc/modules/ROOT/pages/configuration.adoc
> +|The realm to use for authentication. *NOT RECOMMENDED* for security reasons.
Should this also be added to the `user` and `password` configs above?

2024-04-09 07:45 UTC, robsdedude commented on docs/src/main/asciidoc/modules/ROOT/pages/configuration.adoc
> +* `basic` for basic authentication.
The default value is listed in the column to the right. If you saw this and still find an explicit mention of this being the default, I'm happy to change it.

2024-04-09 07:53 UTC, michael-simons commented on docs/src/main/asciidoc/modules/ROOT/pages/configuration.adoc
> +* `basic` for basic authentication.
Aaaah, sure.
I just thought it would be helpful for that specific one to have a small note so that users don't think if or if not to configure this, because `basic` is implied.

2024-04-09 08:52 UTC, robsdedude commented on neo4j-jdbc/src/main/java/org/neo4j/jdbc/Neo4jDriver.java
> +		public String toString() {
I decided to copy what sslMode does (has a `name` property and does case-insensitive string parsing).

2024-04-09 09:45 UTC, michael-simons approved these changes, later dismissed
Happy to merge if you fix the conflicts.

2024-04-09 09:45 UTC, michael-simons commented on neo4j-jdbc/src/main/java/org/neo4j/jdbc/Neo4jDriver.java
> +		public String getName() {
👍

2024-04-09 09:45 UTC, michael-simons commented on neo4j-jdbc/src/test/java/org/neo4j/jdbc/Neo4jDriverUrlParsingTests.java
> +	private static Stream<Arguments> authSchemeProvider() {
Nice reuse of that.

2024-04-10 07:42 UTC, michael-simons approved these changes

2024-04-10 07:43 UTC, merged